
server:
  port: 5001
  tomcat:
    max-http-form-post-size: 20971520 #20MB in Bytes

spring:
  application:
    name: inService
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: yunusaouam22@gmail.com
    password: waiqxnmzefgmlmrr
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  data:
    mongodb:
      database: inService_test
      host: localhost
      port: 27017

  main:
    allow-circular-references: true

# Optional: logging level
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG